### ISSUE TITLE
Rebel C-3PO crew cost not fixed in issue #525.

### ISSUE THREAD

**Issue by JediOswald** [guidokessels/xwing-data2#526] opened 2022-03-04 16:17 UTC
C-3PO crew in rebels should be 7 points, 6 in republic, 5 in resistance. C-3PO crew in rebels is still listed as 6 points even though in issue #525 it was said to be fixed, which it isn't
![3PO](https://user-images.githubusercontent.com/87926233/156799586-537bba5b-3fea-4d45-92a3-d265d7b4dbf8.PNG)
.

**Comment by danrs** [comment] 2022-03-04 23:22
Duplicate of #524

**Closed by danrs** 2022-03-04 23:22 UTC
